'use strict';
const VB={w:810,h:1012}, KEY='pazkids-design-v3';
const S={cat:null,view:'front',patches:[],selected:null,counter:1,drag:null,activeCat:'Letras',activeColl:null,cache:new Map(),meta:new Map()};
const D={logo:$('#brandLogo'),svg:$('#svg'),jacket:$('#jacket'),items:$('#items'),front:$('#frontBtn'),back:$('#backBtn'),controls:$('#controls'),collection:$('#collection'),name:$('#name'),nameView:$('#nameView'),tabs:$('#tabs'),grid:$('#patchGrid'),summary:$('#summary'),toast:$('#toast')};
function $(id){return document.querySelector(id)}
function E(n){return document.createElementNS('http://www.w3.org/2000/svg',n)}
function uid(){return `p-${Date.now()}-${S.counter++}`}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function toast(m){D.toast.textContent=m;D.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>D.toast.classList.remove('show'),2600)}
async function init(){try{S.cat=await (await fetch('catalogo.json',{cache:'no-store'})).json();S.activeColl=(S.cat.letterCollections.find(c=>c.principal)||S.cat.letterCollections[0]).id;D.logo.src=S.cat.brand.logo;bind();renderSelectors();renderCats();renderGrid();render();toast('Personalizador listo.');preloadEssential();}catch(e){console.error(e);toast('No pude iniciar. Revisa catalogo.json y assets.')}}
function paths(){const set=new Set([S.cat.brand.logo,S.cat.jackets.front,S.cat.jackets.back]);S.cat.patches.forEach(p=>set.add(p.imagen));S.cat.letterCollections.forEach(c=>Object.values(c.letters).forEach(x=>set.add(x)));return [...set]}
async function preloadEssential(){await ensureCached([S.cat.brand.logo,S.cat.jackets.front,S.cat.jackets.back]);D.logo.src=src(S.cat.brand.logo);render();}
async function ensureCached(list){const unique=[...new Set(list.filter(Boolean))].filter(p=>!S.cache.has(p));await Promise.all(unique.map(async p=>{try{const b=await (await fetch(p,{cache:'force-cache'})).blob();const d=await blobUrl(b);const m=await imgMeta(d);S.cache.set(p,d);S.meta.set(p,m)}catch(e){console.warn('No cargó',p,e)}}))}
function blobUrl(b){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(b)})}
function imgMeta(u){return new Promise(res=>{const i=new Image();i.onload=()=>res({w:i.naturalWidth||1,h:i.naturalHeight||1});i.onerror=()=>res({w:1,h:1});i.src=u})}
function src(p){return S.cache.get(p)||p}
function coll(id=S.activeColl){return S.cat.letterCollections.find(c=>c.id===id)||S.cat.letterCollections[0]}
function item(id){return S.cat.patches.find(p=>p.id===id)}
function imgPath(p){return p.kind==='letter'?coll(p.collectionId)?.letters[p.letter]:item(p.catalogId)?.imagen}
function nameOf(p){return p.kind==='letter'?`Letra ${p.letter} (${coll(p.collectionId)?.nombre||'Letras'})`:(item(p.catalogId)?.nombre||'Parche')}
function sizeOf(path,size){const m=S.meta.get(path)||{w:1,h:1};const r=m.w/Math.max(1,m.h);return r>=1?{w:size,h:size/r}:{w:size*r,h:size}}
function render(){renderJacket();renderItems();renderSummary();D.front.classList.toggle('active',S.view==='front');D.back.classList.toggle('active',S.view==='back')}
function renderJacket(){D.jacket.innerHTML='';const im=E('image'),p=S.cat.jackets[S.view];im.setAttribute('href',src(p));im.setAttribute('x','20');im.setAttribute('y','26');im.setAttribute('width','770');im.setAttribute('height','960');im.setAttribute('preserveAspectRatio','xMidYMid meet');D.jacket.appendChild(im)}
function renderItems(){D.items.innerHTML='';S.patches.filter(p=>p.view===S.view).forEach(p=>{const path=imgPath(p);if(!path)return;const s=sizeOf(path,p.size),g=E('g');g.classList.add('node');g.dataset.id=p.id;g.setAttribute('transform',`translate(${p.x} ${p.y}) rotate(${p.rotation})`);if(p.id===S.selected){const r=E('rect');r.setAttribute('x',-s.w/2-8);r.setAttribute('y',-s.h/2-8);r.setAttribute('width',s.w+16);r.setAttribute('height',s.h+16);r.setAttribute('rx','12');r.setAttribute('fill','none');r.setAttribute('stroke','#ed7f76');r.setAttribute('stroke-width','4');r.setAttribute('stroke-dasharray','9 7');g.appendChild(r)}const im=E('image');im.setAttribute('href',src(path));im.setAttribute('x',-s.w/2);im.setAttribute('y',-s.h/2);im.setAttribute('width',s.w);im.setAttribute('height',s.h);im.setAttribute('preserveAspectRatio','xMidYMid meet');g.appendChild(im);const hit=E('rect');hit.setAttribute('x',-s.w/2-14);hit.setAttribute('y',-s.h/2-14);hit.setAttribute('width',s.w+28);hit.setAttribute('height',s.h+28);hit.setAttribute('rx','16');hit.setAttribute('fill','transparent');g.appendChild(hit);g.addEventListener('pointerdown',down);D.items.appendChild(g)});D.controls.hidden=!selected()}
function renderSelectors(){D.collection.innerHTML='';S.cat.letterCollections.forEach(c=>{const o=document.createElement('option');o.value=c.id;o.textContent=c.principal?`${c.nombre} (principal)`:c.nombre;o.selected=c.id===S.activeColl;D.collection.appendChild(o)})}
function categories(){return ['Letras',...new Set(S.cat.patches.map(p=>p.categoria))]}
function renderCats(){D.tabs.innerHTML='';categories().forEach(c=>{const b=document.createElement('button');b.textContent=c;b.className=c===S.activeCat?'active':'';b.onclick=()=>{S.activeCat=c;renderCats();renderGrid()};D.tabs.appendChild(b)})}
function renderGrid(){D.grid.innerHTML='';if(S.activeCat==='Letras'){const c=coll();'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').forEach(L=>{const p=c.letters[L];if(!p)return;D.grid.appendChild(card(p,`Letra ${L}`,()=>{addLetter(L,S.view,405,S.view==='front'?590:560,c.defaultSize||62,c.id);render();toast(`Letra ${L} agregada.`)}))});return}S.cat.patches.filter(p=>p.categoria===S.activeCat).forEach(p=>D.grid.appendChild(card(p.imagen,p.nombre,()=>addCatalog(p.id))))}
function card(path,alt,fn){const b=document.createElement('button');b.className='patch-item';b.type='button';b.title=alt;const i=document.createElement('img');i.loading='lazy';i.decoding='async';i.src=src(path);i.alt=alt;i.onload=()=>{if(!S.meta.has(path))S.meta.set(path,{w:i.naturalWidth||1,h:i.naturalHeight||1})};b.appendChild(i);b.onclick=fn;return b}
function addCatalog(id){const it=item(id);if(!it)return;const n=S.patches.filter(p=>p.view===S.view).length;const p={id:uid(),kind:'patch',catalogId:id,view:S.view,x:clamp(405+(n%5)*18-36,70,740),y:clamp(590+(n%7)*16-48,90,930),size:it.defaultSize||76,rotation:0};S.patches.push(p);S.selected=p.id;render();toast(`${it.nombre} agregado.`)}
function addLetter(L,view=S.view,x=405,y=570,size=62,collectionId=S.activeColl){const c=coll(collectionId);if(!c?.letters[L])return null;const p={id:uid(),kind:'letter',letter:L,collectionId:c.id,view,x,y,size,rotation:0};S.patches.push(p);S.selected=p.id;return p}
function createName(){const raw=D.name.value.trim().toUpperCase();if(!raw){toast('Escribe un nombre o agrega letras una por una.');return}const clean=raw.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z ]/g,'').replace(/\s+/g,' ').trim();const c=coll();let view=D.nameView.value;if(view==='current')view=S.view;const chars=[...clean];const maxW=650,gap=10,base=Math.min(68,Math.max(44,(maxW-gap*(chars.length-1))/Math.max(chars.length,1))),step=base*.82+gap;let total=chars.reduce((s,ch)=>s+(ch===' '?step*.65:step),0)-gap,x=405-total/2,created=0;chars.forEach(ch=>{if(ch===' '){x+=step*.65;return}if(c.letters[ch]){addLetter(ch,view,x+step/2,view==='front'?590:560,base,c.id);created++}x+=step});if(!created){toast('No encontré letras compatibles en esta colección.');return}S.view=view;render();toast(`${created} letras agregadas con ${c.nombre}.`)}
function point(e){const r=D.svg.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*VB.w,y:(e.clientY-r.top)/r.height*VB.h}}
function down(e){e.preventDefault();const id=e.currentTarget.dataset.id,p=S.patches.find(x=>x.id===id);if(!p)return;const q=point(e);S.selected=id;S.drag={id,pointerId:e.pointerId,dx:q.x-p.x,dy:q.y-p.y};try{D.svg.setPointerCapture(e.pointerId)}catch{}render()}
function move(e){if(!S.drag)return;e.preventDefault();const p=S.patches.find(x=>x.id===S.drag.id);if(!p)return;const q=point(e);p.x=clamp(q.x-S.drag.dx,20,VB.w-20);p.y=clamp(q.y-S.drag.dy,20,VB.h-20);renderItems();renderSummary()}
function up(){if(!S.drag)return;try{D.svg.releasePointerCapture(S.drag.pointerId)}catch{}S.drag=null;renderSummary()}
function bgClick(e){if(e.target.closest&&e.target.closest('.node'))return;S.selected=null;render()}
function selected(){return S.patches.find(p=>p.id===S.selected)}
function resize(d){const p=selected();if(!p)return;p.size=clamp(p.size+d,28,220);render()}
function rotate(d){const p=selected();if(!p)return;p.rotation=(p.rotation+d+360)%360;render()}
function duplicate(){const p=selected();if(!p)return;const c={...p,id:uid(),x:p.x+28,y:p.y+28};S.patches.push(c);S.selected=c.id;render()}
function del(){const p=selected();if(!p)return;S.patches=S.patches.filter(x=>x.id!==p.id);S.selected=null;render()}
function layer(to){const i=S.patches.findIndex(p=>p.id===S.selected);if(i<0)return;const [p]=S.patches.splice(i,1);to==='front'?S.patches.push(p):S.patches.unshift(p);render()}
function otherView(){const p=selected();if(!p)return;p.view=p.view==='front'?'back':'front';S.view=p.view;render()}
function renderSummary(){if(!S.patches.length){D.summary.textContent='Aún no has agregado parches.';return}const f=S.patches.filter(p=>p.view==='front').length,b=S.patches.filter(p=>p.view==='back').length,sel=selected();D.summary.innerHTML=`Tienes <strong>${S.patches.length}</strong> elemento(s): <strong>${f}</strong> al frente y <strong>${b}</strong> en la espalda.${sel?` Seleccionado: <strong>${esc(nameOf(sel))}</strong>.`:''}`}
function save(){localStorage.setItem(KEY,JSON.stringify({patches:S.patches,counter:S.counter}));toast('Diseño guardado en este dispositivo.')}
function load(){const raw=localStorage.getItem(KEY);if(!raw){toast('No hay diseño guardado.');return}try{const x=JSON.parse(raw);S.patches=Array.isArray(x.patches)?x.patches:[];S.counter=x.counter||S.counter;S.selected=null;render();toast('Diseño cargado.')}catch{toast('No pude cargar el diseño guardado.')}}
function clearAll(){if(!S.patches.length){toast('El diseño ya está limpio.');return}if(confirm('¿Limpiar toda la personalización?')){S.patches=[];S.selected=null;render();toast('Diseño limpiado.')}}
function orderText(){const lines=[`Hola, quiero pedir una chaqueta personalizada de ${S.cat.brand.name}.`,'',`Elementos en frente: ${S.patches.filter(p=>p.view==='front').length}`];S.patches.filter(p=>p.view==='front').forEach((p,i)=>lines.push(`${i+1}. ${nameOf(p)} | x:${Math.round(p.x)} y:${Math.round(p.y)} tamaño:${Math.round(p.size)} giro:${Math.round(p.rotation)}°`));lines.push('',`Elementos en espalda: ${S.patches.filter(p=>p.view==='back').length}`);S.patches.filter(p=>p.view==='back').forEach((p,i)=>lines.push(`${i+1}. ${nameOf(p)} | x:${Math.round(p.x)} y:${Math.round(p.y)} tamaño:${Math.round(p.size)} giro:${Math.round(p.rotation)}°`));lines.push('','Voy a adjuntar la imagen descargada del diseño para confirmar talla, precio y disponibilidad.');return lines.join('\n')}
function whatsapp(){if(!S.patches.length){toast('Primero agrega letras o parches.');return}window.open(`https://wa.me/${S.cat.brand.whatsappNumber}?text=${encodeURIComponent(orderText())}`,'_blank','noopener,noreferrer')}
async function download(){S.selected=null;const used=[S.cat.jackets[S.view],...S.patches.filter(p=>p.view===S.view).map(imgPath)];toast('Preparando imagen para descarga...');await ensureCached(used);render();await new Promise(r=>requestAnimationFrame(r));const clone=D.svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('width','1080');clone.setAttribute('height','1350');clone.setAttribute('viewBox','0 0 810 1012');const blob=new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob);try{const im=await loadImg(url),c=document.createElement('canvas');c.width=1080;c.height=1350;const ctx=c.getContext('2d'),g=ctx.createLinearGradient(0,0,1080,1350);g.addColorStop(0,'#d8f4f3');g.addColorStop(.58,'#f9e9da');g.addColorStop(1,'#f7cbd5');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(im,0,0,c.width,c.height);const png=await new Promise(r=>c.toBlob(r,'image/png',.95));const a=document.createElement('a'),u=URL.createObjectURL(png);a.href=u;a.download=`pazkids-chaqueta-${S.view}.png`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Imagen descargada. Adjunta ese archivo en WhatsApp.')}catch(e){console.error(e);toast('No pude descargar la imagen.')}finally{URL.revokeObjectURL(url)}}
function loadImg(u){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=u})}
function bind(){D.front.onclick=()=>{S.view='front';S.selected=null;render()};D.back.onclick=()=>{S.view='back';S.selected=null;render()};D.collection.onchange=()=>{S.activeColl=D.collection.value;renderGrid()};D.name.oninput=()=>D.name.value=D.name.value.toUpperCase();$('#createName').onclick=createName;D.name.onkeydown=e=>{if(e.key==='Enter')createName()};D.svg.addEventListener('pointermove',move);D.svg.addEventListener('pointerup',up);D.svg.addEventListener('pointercancel',up);D.svg.addEventListener('click',bgClick);$('#smaller').onclick=()=>resize(-8);$('#bigger').onclick=()=>resize(8);$('#rotL').onclick=()=>rotate(-15);$('#rotR').onclick=()=>rotate(15);$('#dup').onclick=duplicate;$('#frontLayer').onclick=()=>layer('front');$('#backLayer').onclick=()=>layer('back');$('#otherView').onclick=otherView;$('#del').onclick=del;$('#save').onclick=save;$('#load').onclick=load;$('#clear').onclick=clearAll;$('#whatsapp').onclick=whatsapp;$('#download').onclick=download}
init();
